config/routes.rb
Rails.application.routes.draw do

  # Static Pages
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  # User Handling
  resources :users
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get 'sessions/new'

  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :weather_stations
  resources :weather_reports

  root 'weather_stations#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/weather_station.rb
class WeatherStation < ApplicationRecord
  belongs_to :user
  has_many :weather_reports

  # Query Darksky.net for each of the historical dates specified, 
  # plus the forecast, in order to compute the risk of landslides
  def update_from_darksky(historical_dates=[Date.today-1], forecast=true)
    darksky_secret = ApiKey.where(:service => 'Darksky').first.key
    hydra = Typhoeus::Hydra.new
    requests = Hash.new
    forecast_request = nil

    logger.debug("Updating Station #{name} for dates: #{historical_dates}")
    
    # Construct the HTTP requests to Darksky: one for each of the past days we care about, and one for today to get the forecast
    historical_dates.each do |d|
        endpoint = "https://api.darksky.net/forecast/#{darksky_secret}/#{self.latitude},#{self.longitude},#{d.to_time.to_i}"
        request = Typhoeus::Request.new(endpoint) 
        hydra.queue(request)
        requests[d] = request
    end
    forecast_request = Typhoeus::Request.new("https://api.darksky.net/forecast/#{darksky_secret}/#{self.latitude},#{self.longitude}")
    hydra.queue(forecast_request) if forecast

    # Run the whole lot of them!
    hydra.run

    # Parse out the observed precipitation from the historical queries
    reports = []
    requests.each_pair do |d, request|
        if request.response.timed_out?
            logger.error "Request to Darksky timed out: #{request}"
            next
        end
        if request.response.nil?
            logger.error "No response from Darksky for request #{request}"
            next
        end
        if request.response.code != 200
            logger.error "Unable to fetch weather data from #{request.base_url}: #{request.response.code} #{request.response.status_message}"
            next
        end

        # With error trapping done, let's parse the body and update the db with the report data.
        data = JSON.load(request.response.body)
        data['daily']['data'].each do |report|
            logger.debug(report)
            d = Time.at(report['time']).to_date
            datestamp = "#{d.year}#{d.month.to_s.rjust(2,'0')}#{d.day.to_s.rjust(2,'0')}"
            logger.debug("Using timestamp #{datestamp}")
            # We want to update an existing row in place if we've previously computed one
            r = weather_reports.find_or_create_by(
                :latitude => self.latitude,
                :longitude => self.longitude,
                :date => datestamp,
            )
            
            
            # TODO: multiply by the actual number of hours in the time period.
            precip = report['precipIntensity'] # This is in inches per hour
            logger.debug("Extracted precipitation report: #{precip} from report #{report}")
            r.precip = precip * 24.0
            logger.debug("Constructed WeatherReport: #{r}")
            logger.debug("Coordinates: #{r.latitude},#{r.longitude}")
            logger.debug("Datestamp: #{r.date}")
            logger.debug("Recorded Precip: #{r.precip}")
            
            r.save
            reports.push(r)
        end
    end

    # Add the forecast data as well
    forecasts = []
    if forecast
      logger.info("Parsing forecasts for station #{self}")
      logger.debug("Got response: #{forecast_request.response}")
      if forecast_request.response.timed_out?
        logger.error "Request to Darksky timed out: #{forecast_request}"
        return
      end
      if forecast_request.response.nil?
        logger.error "No response from Darksky for request #{forecast_request}"
        return
      end
      if forecast_request.response.code != 200
        logger.error "Unable to fetch weather data from #{forecast_request.base_url}: #{forecast_request.response.code} #{forecast_request.response.message}"
        return
      end

      logger.debug("Successful response from Darksky")
      data = JSON.load(forecast_request.response.body)
      data['daily']['data'].each do |report|
        logger.debug(report)
        d = Time.at(report['time']).to_date
        datestamp = "#{d.year}#{d.month.to_s.rjust(2,'0')}#{d.day.to_s.rjust(2,'0')}"
        r = weather_reports.find_or_create_by(
                  :latitude => self.latitude,
                  :longitude => self.longitude,
                  :date => datestamp,
              )
        r.precip = report['precipIntensity'] * 24.0 # The Darksky report gives us inches per hour

        logger.debug("Created forecast object: #{r}")
        r.save
        forecasts.push(r)
      end
    end

    # TODO: add a column that we can record when this update was last run, for display on the webpage.
    {:reports => reports, :forecasts => forecasts}
  end

  # Fetch the 18 days previous to the specified date, and use those records to
  # compute the risk of landslides for this station.
  def alert(today = Date.today)
    # Pull the previous 18 days' reports
    # These should all be loaded after running update_from_darksky

    # Recent reports are the previous three days
    recent_precip = 0.0
    logger.info("Computing Recent Precip for Station #{self} on #{today}")
    recent_weather_reports(today).each do |report|
      recent_precip += report.precip_inches
    end
    logger.debug("Got #{recent_precip} inches of precipitation in the three prior days.")
    # Old reports are the 15 days prior to the 3 days' "recent reports". So, days d - 4 through d - 18
    old_precip = 0.0
    old_weather_reports(today).each do |report|
      old_precip += report.precip_inches
    end
    logger.debug("Got #{old_precip} inches of precipitation in the 15 days before that.")
    
    threshold_level = 3.5 - 0.67 * old_precip
    alert_level = recent_precip - threshold_level
    
    WeatherStationAlert.new(
      :latitude => self.latitude, :longitude => self.longitude, 
      :alert_for => today,
      :level => alert_level,
      :old_sum => old_precip,
      :recent_sum => recent_precip,
    ) 
  end

  # Pull the weather reports for yesterday through today - 3, relative to the given date.
  def recent_weather_reports(today = Date.today)
    recent_days = (1..3).collect {|i| today - i}.collect {|d| "#{d.year}#{d.month.to_s.rjust(2,'0')}#{d.day.to_s.rjust(2,'0')}"}
    weather_reports.where(:date => recent_days)
  end

  # Pull the weather reports for today - 4 through today - 18, relative to the given date.
  def old_weather_reports(today = Date.today)
    old_days = (4..18).collect {|i| today - i}.collect {|d| "#{d.year}#{d.month.to_s.rjust(2,'0')}#{d.day.to_s.rjust(2,'0')}"}
    weather_reports.where(:date => old_days)
  end
end

app/controllers/weather_stations_controller.rb
class WeatherStationsController < ApplicationController
  before_action :set_weather_station, only: [:show, :edit, :update, :destroy]

  # GET /weather_stations
  # GET /weather_stations.json
  def index
    unless logged_in?
      flash.now[:warning] = 'Please log in to view your weather stations'
      redirect_to login_path
    end

    @weather_stations = WeatherStation.all
  end

  # GET /weather_stations/1
  # GET /weather_stations/1.json
  def show
    unless logged_in? && current_user.id == @weather_station.user.id
      flash.now[:warning] = 'Please log in to view your weather stations'
      redirect_to login_path and return
    end

    @weather_reports = @weather_station.weather_reports.all

    @old_days = (4..15).collect do |i|
      d = Date.today - i
      "#{d.year}#{d.month.to_s.rjust(2,'0')}#{d.day.to_s.rjust(2,'0')}"
    end.sort

    @old_reports = {}
    @old_sum = 0.0
    @old_days.each do |d|
      reports = @weather_station.weather_reports.where(:date => d)
      if reports.length > 0
        r = reports.first
        @old_reports[d] = r
        @old_sum += r.precip
      end
    end


    @recent_days = (1..3).collect do |i|
      d = Date.today - i
      "#{d.year}#{d.month.to_s.rjust(2,'0')}#{d.day.to_s.rjust(2,'0')}"
    end.sort

    @recent_reports = {}
    @recent_sum = 0.0
    @recent_days.each do |d|
      reports = @weather_station.weather_reports.where(:date => d)
      if reports.length > 0
        @recent_reports[d] = reports.first
        @recent_sum += @recent_reports[d].precip
      end
    end

    @chart_data = [
        {
            :name => 'Alert Level',
            :data => @alert_forecasts.map {|date, alert| [date, alert.level]}
        },
        {
            :name => 'Precipitation',
            :data => []
        }
    ]

    @weather_reports.each do |r|
      @chart_data[1][:data].push [ Date.parse(r.date), r.precip ] 
    end

    if @alert_today.level > 0
      flash.now[:alert] = "As of yesterday's rainfall, station #{@weather_station.name} is at risk for landslides!!"
    else
      flash.now[:success] = "This station is at low landslide risk"
    end
  end

  # GET /weather_stations/new
  def new
    unless logged_in?
      flash.now[:warning] = 'Please log in to view your weather stations'
      redirect_to login_path and return
    end
    @weather_station = current_user.weather_stations.create
  end

  # GET /weather_stations/1/edit
  def edit
    unless logged_in? && current_user.id == @weather_station.user.id
      flash.now[:warning] = 'Please log in to view your weather stations'
      redirect_to login_path
    end
  end

  # POST /weather_stations
  # POST /weather_stations.json
  def create
    unless logged_in?
      render :file => 'public/401', :status => :unauthorized, :layout => false and return
    end

    @user = User.find(weather_station_params[:user_id])
    @weather_station = @user.weather_stations.create(weather_station_params)

    respond_to do |format|
      if @weather_station.save
        # Automatically update the station with weather reports
        historical_dates = (1..18).collect {|i| Date.today - i}
        @weather_station.update_from_darksky(historical_dates, true)

        format.html { redirect_to @weather_station, notice: 'Weather station was successfully created.' }
        format.json { render :show, status: :created, location: @weather_station }
      else
        format.html { render :new }
        format.json { render json: @weather_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weather_stations/1
  # PATCH/PUT /weather_stations/1.json
  def update
    unless logged_in? && current_user.id == @weather_station.user.id
      # debugger
      render :file => 'public/401', :status => :unauthorized, :layout => false and return
    end

    respond_to do |format|
      if @weather_station.update(weather_station_params)
        # Automatically update the station with weather reports
        historical_dates = (1..18).collect {|i| Date.today - i}
        @weather_station.update_from_darksky(historical_dates, true)

        format.html { redirect_to @weather_station, notice: 'Weather station was successfully updated.' }
        format.json { render :show, status: :ok, location: @weather_station }
      else
        format.html { render :edit }
        format.json { render json: @weather_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weather_stations/1
  # DELETE /weather_stations/1.json
  def destroy
    unless logged_in? && current_user.id == @weather_station.user.id
      render :file => 'public/401', :status => :unauthorized, :layout => false and return
    end

    @weather_station.destroy
    respond_to do |format|
      format.html { redirect_to weather_stations_url, notice: 'Weather station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather_station
      if logged_in?
        begin
          @weather_station = current_user.weather_stations.find(params[:id])
        rescue ActiveRecord::RecordNotFound
          render :file => 'public/401', :status => :unauthorized, :layout => false and return
        end
        @alert_today = @weather_station.alert
        @alert_forecasts = {}
        (0..7).each do |i|
          d = Date.today + i
          @alert_forecasts[d] = @weather_station.alert(d)
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weather_station_params
      params.require(:weather_station).permit(:latitude, :longitude, :name, :user_id)
    end
end

app/helpers/weather_stations_helper.rb
module WeatherStationsHelper
end

app/views/weather_stations/_form.html.erb
<%= form_for(weather_station) do |f| %>
  <% if weather_station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weather_station.errors.count, "error") %> prohibited this weather_station from being saved:</h2>

      <ul>
      <% weather_station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weather_stations/edit.html.erb
<h1>Editing Weather Station</h1>

<%= render 'form', weather_station: @weather_station %>

<%= link_to 'Show', @weather_station %> |
<%= link_to 'Back', weather_stations_path %>

app/views/weather_stations/index.html.erb
<div class="center jumbotron">
    <h1>Weather Stations</h1>
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lat/Long</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @weather_stations.each do |weather_station| %>
      <tr>
        <td><%= weather_station.name %></td>
        <td><%= weather_station.latitude %>,<%= weather_station.longitude %></td>
        <td><%= link_to 'Show', weather_station %></td>
        <td><%= link_to 'Edit', edit_weather_station_path(weather_station) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weather Station', new_weather_station_path %>

app/views/weather_stations/new.html.erb
<h1>New Weather Station</h1>

<%= render 'form', weather_station: @weather_station %>

<%= link_to 'Back', weather_stations_path %>

app/views/weather_stations/show.html.erb
<div class="center jumbotron">
  <h1>Station Report: <%= @weather_station.name %></h1>
  <%= link_to 'Edit', edit_weather_station_path(@weather_station) %> | <%= link_to 'Back to stations list', weather_stations_path %>

  <p>
    <strong>Lat/Long:</strong>
    <%= @weather_station.latitude %>,<%= @weather_station.longitude %>
  </p>
</div>



<h2>Landslide Forecasts for this station</h2>
<p>
  All precipitation numbers are in inches of liquid water.
</p>
<div class="weather-reports">
  <table>
    <tr>
      <th>Date</th>
      <th>Alert Level</th>
      <th>Recent Precip (P3)</th>
      <th>Older Precip (P15)</th>
      <th>Status</th>
    </tr>
    <tr>
      <td>Today</td>
      <td class="alert-<%= (@alert_today.level >= 0) ? 'on' : 'off' %>"><%= @alert_today.level.round(2) %></td>
      <td><%= @alert_today.recent_sum.round(2) %></td>
      <td><%= @alert_today.old_sum.round(2) %></td>
      <td><%= @alert_today.level_description %></td>
    </tr>
    <% @alert_forecasts.each_pair do |date, alert| %>
    <tr>
      <td><%= date %></td>
      <td class="alert-<%= (alert.level >= 0) ? 'on' : 'off' %>"><%= alert.level.round(2) %></td>
      <td><%= alert.recent_sum.round(2) %></td>
      <td><%= alert.old_sum.round(2) %></td>
      <td><%= alert.level_description %></td>
    </tr>
    <% end %>
  </table>
</div>

<h2>Alerts Chart</h2>
<%= line_chart @chart_data %>

<h2>Weather Reports from this station</h2>
<div class="weather-reports">
  <table>
    <tr>
      <th>Date</th>
      <th>Precip (inches)</th>
    </tr>
    <% @weather_reports.each do |r| %>
    <tr>
      <td><%= r.date %></td>
      <td><%= r.precip_inches %></td>
    </tr>
    <% end %>
  </table>
</div>

<h2>Weather Reports from days Today - 4 through Today - 15</h2>
<div class="weather-reports">
  <table>
    <tr>
      <th>Date</th>
      <th>Precip (inches)</th>
    </tr>

    <% @old_days.each do |d| %>
        <tr>
          <td><%= d %></td>
          <td><%= (@old_reports.has_key?(d)) ? @old_reports[d].precip_inches : '' %></td>
        </tr>
    <% end %>
    <tr>
      <th>Sum</th>
      <th><%= @old_sum %></th>
    </tr>
  </table>
</div>

<h2>Weather Reports from Yesterday through Today - 3</h2>
<div class="weather-reports">
  <table>
    <tr>
      <th>Date</th>
      <th>Precip (inches)</th>
    </tr>

    <% @recent_days.each do |d| %>
        <tr>
          <td><%= d %></td>
          <td><%= (@recent_reports.has_key?(d)) ? @recent_reports[d].precip_inches : '' %></td>
        </tr>
    <% end %>
    <tr>
      <th>Sum</th>
      <th><%= @recent_sum %></th>
    </tr>
  </table>
</div>