config/routes.rb
Rails.application.routes.draw do

  # Static Pages
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  # User Handling
  resources :users
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get 'sessions/new'

  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :weather_stations
  resources :weather_reports

  root 'weather_stations#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/weather_report.rb
class WeatherReport < ApplicationRecord
  belongs_to :weather_station

  def precip_inches
    # Darksky reports precip in inches by default for US locations
    return self.precip
  end
end

app/controllers/weather_reports_controller.rb
class WeatherReportsController < ApplicationController
  before_action :set_weather_report, only: [:show, :edit, :update, :destroy]

  # GET /weather_reports
  # GET /weather_reports.json
  def index
    @weather_reports = WeatherReport.all
  end

  # GET /weather_reports/1
  # GET /weather_reports/1.json
  def show
  end

  # GET /weather_reports/new
  def new
    @weather_report = WeatherReport.new
  end

  # GET /weather_reports/1/edit
  def edit
  end

  # POST /weather_reports
  # POST /weather_reports.json
  def create
    # @weather_report = WeatherReport.new(weather_report_params)
    #
    # respond_to do |format|
    #   if @weather_report.save
    #     format.html { redirect_to @weather_report, notice: 'Weather report was successfully created.' }
    #     format.json { render :show, status: :created, location: @weather_report }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @weather_report.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /weather_reports/1
  # PATCH/PUT /weather_reports/1.json
  def update
    # respond_to do |format|
    #   if @weather_report.update(weather_report_params)
    #     format.html { redirect_to @weather_report, notice: 'Weather report was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @weather_report }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @weather_report.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /weather_reports/1
  # DELETE /weather_reports/1.json
  def destroy
    # @weather_report.destroy
    # respond_to do |format|
    #   format.html { redirect_to weather_reports_url, notice: 'Weather report was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather_report
      @weather_report = WeatherReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weather_report_params
      params.require(:weather_report).permit(:latitude, :longitude, :precip)
    end
end

app/helpers/weather_reports_helper.rb
module WeatherReportsHelper
end

app/views/weather_reports/_form.html.erb
<%= form_for(weather_report) do |f| %>
  <% if weather_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weather_report.errors.count, "error") %> prohibited this weather_report from being saved:</h2>

      <ul>
      <% weather_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :precip %>
    <%= f.text_field :precip %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weather_reports/edit.html.erb
<h1>Editing Weather Report</h1>

<%= render 'form', weather_report: @weather_report %>

<%= link_to 'Show', @weather_report %> |
<%= link_to 'Back', weather_reports_path %>

app/views/weather_reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Weather Reports</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Precip</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @weather_reports.each do |weather_report| %>
      <tr>
        <td><%= weather_report.date %></td>
        <td><%= weather_report.latitude %></td>
        <td><%= weather_report.longitude %></td>
        <td><%= weather_report.precip * 10 %> mm</td>
        <td><%= link_to 'Show', weather_report %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weather Report', new_weather_report_path %>

app/views/weather_reports/new.html.erb
<h1>New Weather Report</h1>

<%= render 'form', weather_report: @weather_report %>

<%= link_to 'Back', weather_reports_path %>

app/views/weather_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @weather_report.date %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @weather_report.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @weather_report.longitude %>
</p>

<p>
  <strong>Precip:</strong>
  <%= @weather_report.precip * 10 %> mm
</p>

<%= link_to 'Back', weather_reports_path %>